# -*- coding: utf-8 -*-
"""dictionary ailen project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bWwYXlh61unKBORUU2rmpi1qMkzQRkkb

###Problem satetment 1

You are given such a tuple vof strings waht will be your approch to decode it

solution :-
   * calculate len of every element in the tuple,store in the new list
   * For space between words the length will be 0.
   * For above example this new list will be [8,9,0,19,1,14,20,1],let's call this list
   * create a dictonary d where key is number from (1 to 26 and 0) and values are(a to z and" "(single space))
   * Using elements of list 1as key of the dictonary create a string of its values and this will be oure message.

###Problem 2

Create a dictonary where the key corresponds to the positon of the alphabet(consider space as the first alphabet) and the value corresponding to the kry will be the alphabet
"""

alphabet_dict ={0:"  ",1:"a",2:"b",3:"c",4:"d",5:"e",6:"f",7:"g",8:"h",9:"i",10:"j",11:"k",12:"l",13:"m",14:"n",15:"o",16:"p",17:"q",18:"r",19:"s",20:"t",21:"u",22:"v",23:"w",24:"x",25:"y",26:"z"}
print(alphabet_dict)

"""###Problem 3

Suppose you are given a particular value from the dictonary. write the code to extract the corresponding key the dictonary
"""

alphabet_dict_keys = list(alphabet_dict.keys())
alphabet_dict_values= list(alphabet_dict.values())
print(alphabet_dict_values)

alphabet_dict_values.index('h')

"""###Problem 4

Scientitists receive the following message code from the ailen civilization
"""

encry_msg=("addf"," ","gjhngjf","gyrgug","bvhbcvjgfh","hggfb")
len(encry_msg)

l=[]
l.append(len(encry_msg[0]))
l.append(len(encry_msg[1]))
l.append(len(encry_msg[2]))
l.append(len(encry_msg[3]))
l.append(len(encry_msg[4]))
l.append(len(encry_msg[5]))

print(l)

decry_msg=" "

decry_msg = decry_msg + alphabet_dict[l[0]]
decry_msg = decry_msg + alphabet_dict[l[1]]
decry_msg = decry_msg + alphabet_dict[l[2]]
decry_msg = decry_msg + alphabet_dict[l[3]]
decry_msg = decry_msg + alphabet_dict[l[4]]
decry_msg = decry_msg + alphabet_dict[l[5]]

print(decry_msg)

"""###Problem 5

Encrypt a msg for the alien civilization which the scientists can send through the EM signals Scientists want to ask the aliens "why"
"""

# print(alphabet_dict_values)
l1 =[]
l1.append(alphabet_dict_values.index('w'))
l1.append(alphabet_dict_values.index('h'))
l1.append(alphabet_dict_values.index('y'))
print(l1)

"""###Problem 6

get the encrypted message using the final list obtained in the above problem where you will use only alphabet "a"
"""

msg =[]
msg.append(l1[0]*'a')
msg.append(l1[1]*'a')
msg.append(l1[2]*'a')
msg = tuple(msg)
print(msg)

"""###Problem 7

Aliens receive the reply from the scientists. They decode the message and send an encrypted message again. Due to some aberrations because of an existing very massive star, one of the words of their message gets transformed into something gibberish/unreadable. They sent the following message:

I sau a some gibberish please help me soon

Scientists were baffled by the presence of such an indecipherable word in the message sent by Aliens. Suddenly they receive another signal from them which contains the gibberish word but this time the letters have been jumbled up. Scientists need to sort the letters of this word in alphabetical order within it to get the actual transmitted word

The encoded list of the unknown word is:

jumbled word "hugdtck", "tsogbklesrawqcbjplu", "qkisrutskuaitht", "nslaoetr", "oksinjicaendnjsdqubh"]
"""

jumbled_word = ["hugdctk", "tsogbklesrawqcbjplu", "qkisrubskoaibtbt", "nslaoetr", "oksinjioaendnjsdqwbh"]

decoded_each = [''.join(sorted(s)) for s in jumbled_word]
for orig, dec in zip(jumbled_word, decoded_each):
    print(orig, "->", dec)

combined = ''.join(jumbled_word)
print("Combined sorted:", ''.join(sorted(combined)))